{% set name = "jlgametheory" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/jlgametheory-{{ version }}.tar.gz
  sha256: 99afe8a0f7c2899d894288cf83d18e632e3463db491c3236f3b560e5f0c0b03c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - quantecon >=0.8
    - pyjuliacall >=0.9.20

test:
  imports:
    - jlgametheory
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/QuantEcon/jlgametheory
  summary: Python interface to GameTheory.jl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oyamad
