{% set name = "jlgametheory" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jlgametheory-{{ version }}.tar.gz
  sha256: e22cf6469e95a01f0882e75130fdc0bf180e5c936da90cf64c2463524a8e39b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - quantecon >=0.8
    - pyjuliacall >=0.9.20

test:
  imports:
    - jlgametheory
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/QuantEcon/jlgametheory
  summary: Python interface to GameTheory.jl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oyamad
