{% set name = "jlgametheory" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/jlgametheory-{{ version }}.tar.gz
  sha256: d62f343fb6760726fa887bce9b27caa2e07def1799c30f12fa2f62ac446a109c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - quantecon >=0.8
    - pyjuliacall >=0.9.20

test:
  imports:
    - jlgametheory
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/QuantEcon/jlgametheory
  summary: Python interface to GameTheory.jl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oyamad
